### ISSUE TITLE
Quote-font-family: 应该优先添加西文字体

### ISSUE THREAD

**Issue by infinnie** [zmmbreeze/Entry.css#21]
<pre>@quote-font-family: STKaiti, KaiTi, serif;</pre>

这样至少在 Windows 下面， blockquote 的西文部分会很崩溃，而且 Windows 的楷体木有粗体支持。

以上。

**Comment by zmmbreeze** [comment]
增加了blockquote的西文字体，没有发现不支持粗体的问题。测试过IE8，9，10，11，win 7和xp，不知道你用的哪个系统
![entrycss](https://cloud.githubusercontent.com/assets/249872/6996041/06c14ee4-dba2-11e4-8085-b0aad5e333f4.png)

**Comment by infinnie** [comment]
Thx, 我是说楷体的粗体就是机械加粗的结果，并不是真正的专门粗体。
:+1: :)
