### ISSUE TITLE
建议：不要在entry类上加入width限制；<h*>标签自动编号功能能否以某种形式关闭？

### ISSUE THREAD

**Issue by fy0** [zmmbreeze/Entry.css#22]
如题。这个width: 960px感觉已经没有必要了，而且大家也会自己去选择自己的width。
<h*>这个功能也是吓了我一跳……但文档上好像没提到如何关闭

**Comment by zmmbreeze** [comment]
Entry.css里面的最大宽度（不包括padding）计算方式是：`@font-size * 40`。

如果你的宽度是960px ，那么你应该是设置了字体为24px吗？另外Entry.css只会设置最大宽度，而不会固定宽度。最好确认下你是不是有其他CSS设置了。

之所以会设置一个最大宽度是因为一行文字如果字数过多阅读时眼睛焦点移动距离过长，为了使用方便故设置一行最多能包含40个字。

如果你想不固定宽度，那么直接增加下面的CSS即可：

```
.entry {
    max-width: none;
}
```

**Comment by fy0** [comment]
@zmmbreeze  呃 这个还是比较easy的，事实上不知道如何关的是<h_>那个功能，由于Markdown带走了html标签，<h_>没有显示出来……

**Comment by zmmbreeze** [comment]
在你自己的配置里面设置`@use-title-number: false;`  

https://github.com/zmmbreeze/Entry.css/blob/master/src/entry-config.less#L67

**Comment by fy0** [comment]
@zmmbreeze 多谢
